# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLVTLz5DwIC0xDDrkmmnUlW23hlxti4u
"""

import requests

API_KEY = 'your_api_key'  # Replace with your actual API key from the exchange rate provider
BASE_URL = 'https://v6.exchangerate-api.com/v6/'

def get_exchange_rate(api_key, from_currency, to_currency):
    url = f"{BASE_URL}{api_key}/pair/{from_currency}/{to_currency}"
    response = requests.get(url)
    data = response.json()

    if response.status_code != 200 or data.get("result") != "success":
        raise Exception(f"Error fetching exchange rate: {data.get('error-type', 'Unknown error')}")

    return data['conversion_rate']

def convert_currency(amount, from_currency, to_currency, rate):
    return amount * rate

def main():
    print("Welcome to the Currency Converter!")

    amount = float(input("Enter the amount to convert: "))
    from_currency = input("Enter the source currency (e.g., USD, EUR): ").upper()
    to_currency = input("Enter the target currency (e.g., USD, EUR): ").upper()

    try:
        rate = get_exchange_rate(API_KEY, from_currency, to_currency)
        converted_amount = convert_currency(amount, from_currency, to_currency, rate)
        print(f"{amount} {from_currency} is equal to {converted_amount:.2f} {to_currency}")
    except Exception as e:
        print(e)

if __name__ == "__main__":
    main()



# Libraries
import requests

# API endpoint (replace with your preferred provider's URL)
api_url = "https://api.exchangerate-api.com/v4/latest"

def get_rate(from_currency, to_currency):
  """Fetches the exchange rate from the API"""
  response = requests.get(f"{api_url}/{from_currency}")
  data = response.json()
  if response.status_code == 200:
    return data["rates"][to_currency]
  else:
    print(f"Error: {data['message']}")
    return None

def convert(amount, from_currency, to_currency):
  """Converts the amount between currencies"""
  rate = get_rate(from_currency, to_currency)
  if rate:
    converted_amount = amount * rate
    print(f"{amount} {from_currency} is equivalent to {converted_amount:.2f} {to_currency}")
  else:
    print("Failed to retrieve conversion rate.")

# Main program
while True:
  amount = float(input("Enter amount: "))
  from_currency = input("From currency (e.g. USD, EUR, JPY): ").upper()
  to_currency = input("To currency (e.g. USD, EUR, JPY): ").upper()
  convert(amount, from_currency, to_currency)
  choice = input("Convert again? (y/n): ").lower()
  if choice != "y":
    break

print("Thank you for using the currency converter!")